### ISSUE TITLE
Generate an initial README

### ISSUE THREAD

**Issue by m8ttyB** [m8ttyB/sux#1]
Create a readme describing why web accessibility is important and outlining the general goals of this project. We'll get more specific as we begin to understand the problem domain and begin to see the solution we want.

- [x] Phase 1 - domain knowledge - learn about web accessibility, the different modalities it coveres (or doesn't cover), and how testing is done. While we're gathering domain knowledge I would also like for us to understand how to make contributing to projects more accessible.
- [x] Phase 2 - research - make a list and explore existing open source libraries that have APIs that we can use for an automated regression testing suite. Ideally the API has support for Python or JS and allow us to use an XUnit framework such as pytest.
- [x] Phase 3 - create - create a suite of regression tests that we can run at will and include as part of a Jenkins pipeline job.

**Comment by mayela** [comment]
Maybe we'll have people with impairments that wanna participate in this project. So how to do accessible documentation?

**Comment by m8ttyB** [comment]
@mayela +:100:. A stretch goal of the internship is to look at how technical projects, this one included, can open up to contribution paths with maximum inclusion in mind.

**Comment by mayela** [comment]
There are many impairments, the time is short so we have to decide which ones we'll work for the internship.

**Comment by m8ttyB** [comment]
@mayela I'll produce a scoping document by next Tuesday.
