### ISSUE TITLE
Review aria-highlighter.js

### ISSUE THREAD

**Issue by m8ttyB** [m8ttyB/sux#13]
Review the highlighter script for correctness and update as required:
* https://github.com/m8ttyB/sux/blob/master/highlighter/src/aria-highlighter.js

**Comment by hamletv** [comment]
Matt,
Didn't notice that this issue was posted and has been for a while. I've been looking at this script on and off for some time. Tested it on sites with and without roles and it seems to work. I'll test again and discuss with you before closing this issue.
