### ISSUE TITLE
Generate a test plan for TDD

### ISSUE THREAD

**Issue by jeanhl** [m8ttyB/sux#3]
Write an initial test plan following the general goals of this project. The test plan can be used as guideline on how we'll develop the project. It'll currently be largely generalized and we'll add to it as the project grows. It should cover:

* **Overall description of the project and our goals.**
  This will keep us on track with an objective in mind as we build the project
* **Scope** 
   What is the scope of our minimal viable project (MVP) and the testing that needs to be done at each stage.
* **General architecture of the project.** 
   The different parts that needs to be done and tested for the MVP. Describe system and integration tests that we should think about.

**Comment by mayela** [comment]
Maybe we could use a platform for begin writing the mvp's tasks. I found this https://clubhouse.io/

**Comment by zeddmaxx** [comment]
Hey! I'll get started on writing the initial test plan and cover all the points listed out by you!
